// <auto-generated />
using System;
using JFjewelery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JFjewelery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626205020_RestructurizationForFilterAndSeeding")]
    partial class RestructurizationForFilterAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JFjewelery.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Earrings"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pendants"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brooches"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chains"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ear cuffs"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hair accessories"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chokers"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pins"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Characteristics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Women",
                            Manufacturer = "JFjewelery",
                            ProductId = 1,
                            Style = "Classic"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.AppliesToEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppliesToEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stone"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.CharacteristicMetal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("MetalId")
                        .HasColumnType("integer");

                    b.Property<int?>("Purity")
                        .HasColumnType("integer");

                    b.Property<int?>("ShapeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("ColorId");

                    b.HasIndex("MetalId");

                    b.HasIndex("ShapeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("TypeId");

                    b.ToTable("CharacteristicMetals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacteristicId = 1,
                            ColorId = 1,
                            MetalId = 1,
                            Purity = 585,
                            ShapeId = 3,
                            SizeId = 2,
                            TypeId = 1,
                            Weight = 10f
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.CharacteristicStone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("ShapeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int>("StoneId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ShapeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StoneId");

                    b.HasIndex("TypeId");

                    b.ToTable("CharacteristicStones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacteristicId = 1,
                            ColorId = 7,
                            Count = 4,
                            ShapeId = 11,
                            SizeId = 5,
                            StoneId = 2
                        },
                        new
                        {
                            Id = 2,
                            CharacteristicId = 1,
                            ColorId = 14,
                            Count = 62,
                            ShapeId = 12,
                            SizeId = 5,
                            StoneId = 7,
                            TypeId = 9
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Coating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliesToEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntityId");

                    b.ToTable("Coating");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToEntityId = 1,
                            Name = "Rhodium Plating"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToEntityId = 1,
                            Name = "Gold Plating"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToEntityId = 1,
                            Name = "Black Rhodium"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToEntityId = 1,
                            Name = "Silver Plating"
                        },
                        new
                        {
                            Id = 5,
                            AppliesToEntityId = 1,
                            Name = "PVD Coating"
                        },
                        new
                        {
                            Id = 6,
                            AppliesToEntityId = 2,
                            Name = "Irradiation"
                        },
                        new
                        {
                            Id = 7,
                            AppliesToEntityId = 2,
                            Name = "Heat Treatment"
                        },
                        new
                        {
                            Id = 8,
                            AppliesToEntityId = 2,
                            Name = "Dyeing"
                        },
                        new
                        {
                            Id = 9,
                            AppliesToEntityId = 2,
                            Name = "Coating with Film"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliesToEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntityId");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToEntityId = 1,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToEntityId = 1,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToEntityId = 1,
                            Name = "Rose Gold"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToEntityId = 1,
                            Name = "White Gold"
                        },
                        new
                        {
                            Id = 5,
                            AppliesToEntityId = 1,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 6,
                            AppliesToEntityId = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 7,
                            AppliesToEntityId = 2,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 8,
                            AppliesToEntityId = 2,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 9,
                            AppliesToEntityId = 2,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 10,
                            AppliesToEntityId = 2,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 11,
                            AppliesToEntityId = 2,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 12,
                            AppliesToEntityId = 2,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 13,
                            AppliesToEntityId = 2,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 14,
                            AppliesToEntityId = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 15,
                            AppliesToEntityId = 2,
                            Name = "Black"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.JType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliesToEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntityId");

                    b.ToTable("Type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToEntityId = 1,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToEntityId = 1,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToEntityId = 1,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToEntityId = 1,
                            Name = "Palladium"
                        },
                        new
                        {
                            Id = 5,
                            AppliesToEntityId = 1,
                            Name = "Titanium"
                        },
                        new
                        {
                            Id = 6,
                            AppliesToEntityId = 2,
                            Name = "Star-shaped"
                        },
                        new
                        {
                            Id = 7,
                            AppliesToEntityId = 2,
                            Name = "Milky"
                        },
                        new
                        {
                            Id = 8,
                            AppliesToEntityId = 2,
                            Name = "Impure"
                        },
                        new
                        {
                            Id = 9,
                            AppliesToEntityId = 2,
                            Name = "Pure"
                        },
                        new
                        {
                            Id = 10,
                            AppliesToEntityId = 2,
                            Name = "Translucent"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Metal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Metal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Titanium"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliesToEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntityId");

                    b.ToTable("Shape");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToEntityId = 1,
                            Name = "Round"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToEntityId = 1,
                            Name = "Square"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToEntityId = 1,
                            Name = "Oval"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToEntityId = 1,
                            Name = "Rectangle"
                        },
                        new
                        {
                            Id = 5,
                            AppliesToEntityId = 1,
                            Name = "Triangle"
                        },
                        new
                        {
                            Id = 6,
                            AppliesToEntityId = 2,
                            Name = "Brilliant Cut"
                        },
                        new
                        {
                            Id = 7,
                            AppliesToEntityId = 2,
                            Name = "Princess Cut"
                        },
                        new
                        {
                            Id = 8,
                            AppliesToEntityId = 2,
                            Name = "Cushion Cut"
                        },
                        new
                        {
                            Id = 9,
                            AppliesToEntityId = 2,
                            Name = "Emerald Cut"
                        },
                        new
                        {
                            Id = 10,
                            AppliesToEntityId = 2,
                            Name = "Marquise Cut"
                        },
                        new
                        {
                            Id = 11,
                            AppliesToEntityId = 2,
                            Name = "Oval"
                        },
                        new
                        {
                            Id = 12,
                            AppliesToEntityId = 2,
                            Name = "Round"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliesToEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntityId");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToEntityId = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToEntityId = 1,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToEntityId = 1,
                            Name = "Large"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToEntityId = 2,
                            Name = "Tiny"
                        },
                        new
                        {
                            Id = 5,
                            AppliesToEntityId = 2,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 6,
                            AppliesToEntityId = 2,
                            Name = "Big"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Stone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emerald"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amethyst"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Topaz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spinel"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentScenario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScenarioStep")
                        .HasColumnType("text");

                    b.Property<string>("TempData")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("JFjewelery.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelegramAcc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JFjewelery.Models.CustomerPaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("CustomerPaymentMethods");
                });

            modelBuilder.Entity("JFjewelery.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JFjewelery.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("JFjewelery.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paypal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blik"
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Ruby rose",
                            Price = 5000,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "prod_1_front_1.jpg",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristic", b =>
                {
                    b.HasOne("JFjewelery.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.CharacteristicMetal", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristic", "Characteristic")
                        .WithMany("Metals")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.Characteristics.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("JFjewelery.Models.Characteristics.Metal", "Metal")
                        .WithMany()
                        .HasForeignKey("MetalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.Characteristics.Shape", "Shape")
                        .WithMany()
                        .HasForeignKey("ShapeId");

                    b.HasOne("JFjewelery.Models.Characteristics.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("JFjewelery.Models.Characteristics.JType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Characteristic");

                    b.Navigation("Color");

                    b.Navigation("Metal");

                    b.Navigation("Shape");

                    b.Navigation("Size");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.CharacteristicStone", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristic", "Characteristic")
                        .WithMany("Stones")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.Characteristics.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("JFjewelery.Models.Characteristics.Shape", "Shape")
                        .WithMany()
                        .HasForeignKey("ShapeId");

                    b.HasOne("JFjewelery.Models.Characteristics.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("JFjewelery.Models.Characteristics.Stone", "Stone")
                        .WithMany()
                        .HasForeignKey("StoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.Characteristics.JType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Characteristic");

                    b.Navigation("Color");

                    b.Navigation("Shape");

                    b.Navigation("Size");

                    b.Navigation("Stone");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Coating", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristics.AppliesToEntity", "AppliesTo")
                        .WithMany()
                        .HasForeignKey("AppliesToEntityId");

                    b.Navigation("AppliesTo");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Color", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristics.AppliesToEntity", "AppliesTo")
                        .WithMany()
                        .HasForeignKey("AppliesToEntityId");

                    b.Navigation("AppliesTo");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.JType", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristics.AppliesToEntity", "AppliesTo")
                        .WithMany()
                        .HasForeignKey("AppliesToEntityId");

                    b.Navigation("AppliesTo");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Shape", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristics.AppliesToEntity", "AppliesTo")
                        .WithMany()
                        .HasForeignKey("AppliesToEntityId");

                    b.Navigation("AppliesTo");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristics.Size", b =>
                {
                    b.HasOne("JFjewelery.Models.Characteristics.AppliesToEntity", "AppliesTo")
                        .WithMany()
                        .HasForeignKey("AppliesToEntityId");

                    b.Navigation("AppliesTo");
                });

            modelBuilder.Entity("JFjewelery.Models.ChatSession", b =>
                {
                    b.HasOne("JFjewelery.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JFjewelery.Models.CustomerPaymentMethod", b =>
                {
                    b.HasOne("JFjewelery.Models.Customer", "Customer")
                        .WithMany("CustomerPaymentMethods")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("CustomerPaymentMethods")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("JFjewelery.Models.Order", b =>
                {
                    b.HasOne("JFjewelery.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("JFjewelery.Models.OrderProduct", b =>
                {
                    b.HasOne("JFjewelery.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JFjewelery.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JFjewelery.Models.Product", b =>
                {
                    b.HasOne("JFjewelery.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JFjewelery.Models.ProductImage", b =>
                {
                    b.HasOne("JFjewelery.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JFjewelery.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JFjewelery.Models.Characteristic", b =>
                {
                    b.Navigation("Metals");

                    b.Navigation("Stones");
                });

            modelBuilder.Entity("JFjewelery.Models.Customer", b =>
                {
                    b.Navigation("CustomerPaymentMethods");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JFjewelery.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("JFjewelery.Models.PaymentMethod", b =>
                {
                    b.Navigation("CustomerPaymentMethods");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JFjewelery.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
